### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [song21677/add_nbo#1]
https://github.com/song21677/add_nbo/commit/889e60b5ef311c7d33bb6fb17a72bac8151ec4e2#r38122253

**Comment by song21677** [comment]
> [889e60b#r38122253](https://github.com/song21677/add_nbo/commit/889e60b5ef311c7d33bb6fb17a72bac8151ec4e2#r38122253)

https://github.com/song21677/add_nbo/commit/4e95e7696ce03698b2d85bf52da6ee9fb93ea210

수정하였습니다!

**Comment by snoopspy** [comment]
수고하셨습니다.
